[project]
name = "layerquantizer"
version = "0.3.2"
description = "LayerQuantizer, a numcodec-compatible quantizer/compressor for multi-layer data"
authors = [{name = "Christopher Subich", email = "christopher.subich@ec.gc.ca"}]
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "numba",
    "numpy",
    "numcodecs",
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/csubich/layerquantizer"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "gcsfs>=2026.1.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "tabulate>=0.9.0",
    "types-setuptools>=80.9.0.20251223",
    "types-tabulate>=0.9.0.20241207",
    "xarray",
    "zarr",
]

[project.entry-points."zarr.codecs"]
"layerquantizer0.3" = "layerquantizer.zarr3_codec:LayerQuantizerCodec"

[project.entry-points."numcodecs.codecs"]
"layerquantizer0.3b" = "layerquantizer.layerquantizer:LayerQuantizer"

[tool.mypy]
ignore_missing_imports = true

